   services:
     - type: web
       name: discord-bot
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: python bot/main.py
       plan: free
       envVars:
         - key: DISCORD_TOKEN
           sync: false
         - key: DISCORD_APPLICATION_ID
           sync: false
         - key: OPENAI_APIKEY
           sync: false
         - key: P_APIKEY
           sync: false
         - key: UnS_APIKEY
           sync: false